#!/bin/bash

# set gnome to display everything in the startup applications menu
sudo sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop
# set numlock to be on
numlockx on

# gnome keyboard shortcuts
gsettings set org.gnome.settings-daemon.plugins.media-keys www "['<Super>f']"
gsettings set org.gnome.settings-daemon.plugins.media-keys home "['<Super>e']"
gsettings set org.gnome.settings-daemon.plugins.media-keys email "[]"
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "[]"
gsettings set org.gnome.mutter.keybindings toggle-tiled-left "[]" 


# custom keyboard shortcuts
# htop
SHORTCUT_PATH="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:${SHORTCUT_PATH}0/ name "Open htop"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:${SHORTCUT_PATH}1/ command "gnome-terminal -- bash -c 'htop'"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:${SHORTCUT_PATH}2/ binding "<Primary><Shift>Escape"



SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# deal with startup apps
mkdir -p ~/.config/autostart
cp $SCRIPT_DIR/autostart/* ~/.config/autostart/

# disable Pop_Shop daemon
echo "X-GNOME-Autostart-enabled=false" >> ~/.config/autostart/io.elementary.appcenter-dae    mon.desktop
cp /etc/xdg/autostart/io.elementary.appcenter-daemon.desktop ~/.config/autostart/

# add some apps to the applications menu
mkdir -p ~/.local/share/applications
cp $SCRIPT_DIR/applications/* ~/.local/share/applications



