#!/bin/bash

echo "UPDATING APT"
sudo apt update && sudo apt upgrade -y
echo "DOWNLOADING APT PACKAGES"
sudo apt -y install neovim mpv vlc syncthing firefox alacritty blueman gnome-bluetooth htop xclip timeshift kdeconnect zsh smartmontools btop neofetch gnome-shell-extension-manager numlockx python3-pip gufw software-properties-common apt-transport-https curl tree openjdk-11-jdk tldr

echo "DOWNLOADING FLATPAK PACKAGES"
flatpak install -y flathub com.usebottles.bottles com.discordapp.Discord com.spotify.Client md.obsidian.Obsidian org.qbittorrent.qBittorrent org.keepassxc.KeePassXC 

echo "SETTING UP MICROSOFT REPOS"
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-archive-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
sudo apt update

sudo apt -y install code

echo "INSTALLING RUST"
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
cargo install vivid

echo "REMOVING USELESS POP-SHOP"
sudo apt remove pop-shop

tldr -u

